import {
  appendResponseRow,
  findRowIndexByResponseId,
  getResponseByRowIndex,
  getResponseRows,
  updateResponseRow,
  type ResponseRow,
} from "./excel";
import { enqueueWrite, markDone, markFailed } from "./syncQueue";
import { getIndexBySubmitter, upsertIndex } from "./responseIndex";
import { addAuditEntry } from "./auditLog";
import type { AnswerValue, AuditEntry, FormDefinition, FormResponse } from "../formsSchema/types";

function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function diffAnswers(
  before: Record<string, AnswerValue>,
  after: Record<string, AnswerValue>
): AuditEntry["changedFields"] {
  const fieldIds = new Set([...Object.keys(before), ...Object.keys(after)]);
  const changed: AuditEntry["changedFields"] = [];
  for (const fieldId of fieldIds) {
    const oldValue = before[fieldId] ?? null;
    const newValue = after[fieldId] ?? null;
    if (JSON.stringify(oldValue) !== JSON.stringify(newValue)) {
      changed.push({ fieldId, oldValue, newValue });
    }
  }
  return changed;
}

/**
 * Submits a fresh response: SyncQueue-first (durable regardless of what
 * happens next), then attempts the Excel append with a few retries. Even if
 * every Excel attempt fails, the response is NOT lost — it stays recorded in
 * SyncQueue as "failed" for the admin Sync Health page to recover, and the
 * caller still gets back a normal FormResponse rather than an error, matching
 * the plan's "tell the user submitted either way" durability model.
 */
export async function submitResponse(
  form: FormDefinition,
  answers: Record<string, AnswerValue>,
  respondentUpn: string,
  /** Pre-generated by the caller (FillRunner needs it up front for
   *  file-attachment upload paths) so it matches the id those files were
   *  actually uploaded under. Falls back to a fresh one if omitted. */
  responseId: string = crypto.randomUUID()
): Promise<FormResponse> {
  const now = new Date().toISOString();
  const response: FormResponse = {
    id: responseId,
    formId: form.id,
    formVersion: form.latestPublishedVersion ?? form.currentDraftVersion,
    respondentUpn,
    answers,
    status: "submitted",
    submittedAt: now,
    updatedAt: now,
    editHistory: [],
  };

  const queueItemId = await enqueueWrite({
    formId: form.id,
    responseId: response.id,
    submitterEmail: respondentUpn,
    operation: "insert",
    payload: response,
  });

  const maxAttempts = 3;
  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    try {
      await appendResponseRow(form, response);
      await markDone(queueItemId);
      const rowIndex = await findRowIndexByResponseId(form, response.id);
      if (rowIndex !== null) {
        await upsertIndex({ formId: form.id, responseId: response.id, submitterEmail: respondentUpn, rowIndex });
      }
      await addAuditEntry({
        formId: form.id,
        responseId: response.id,
        byEmail: respondentUpn,
        action: "submit",
        changedFields: Object.entries(answers).map(([fieldId, newValue]) => ({ fieldId, oldValue: null, newValue })),
      });
      return response;
    } catch (err) {
      if (attempt === maxAttempts) {
        await markFailed(queueItemId, attempt, err instanceof Error ? err.message : String(err));
      } else {
        await sleep(500 * attempt);
      }
    }
  }

  return response;
}

/** The existing-response gate: does this email already have a response to
 *  this form? Email is the primary key, per the product's core requirement. */
export async function getMyResponse(
  form: FormDefinition,
  email: string
): Promise<{ response: FormResponse; rowIndex: number } | null> {
  const indexEntry = await getIndexBySubmitter(form.id, email);
  if (!indexEntry) return null;
  const response = await getResponseByRowIndex(form, indexEntry.fields.RowIndex);
  if (!response) return null;
  return { response, rowIndex: indexEntry.fields.RowIndex };
}

/**
 * Edits an existing response (self-edit or admin-edit — the caller decides
 * which based on the form's editPolicy and who's editing). Same SyncQueue-
 * first durability model as submitResponse, plus an audit trail entry
 * recording exactly what changed.
 */
export async function updateResponse(params: {
  form: FormDefinition;
  existing: FormResponse;
  rowIndexHint: number;
  answers: Record<string, AnswerValue>;
  editorEmail: string;
  reason?: string;
}): Promise<FormResponse> {
  const { form, existing, answers, editorEmail } = params;
  const changedFields = diffAnswers(existing.answers, answers);

  const updated: FormResponse = {
    ...existing,
    answers,
    updatedAt: new Date().toISOString(),
  };

  const queueItemId = await enqueueWrite({
    formId: form.id,
    responseId: updated.id,
    submitterEmail: updated.respondentUpn,
    operation: "update",
    payload: updated,
  });

  const maxAttempts = 3;
  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    try {
      const rowIndex = await updateResponseRow(form, updated, params.rowIndexHint, editorEmail);
      await markDone(queueItemId);
      await upsertIndex({ formId: form.id, responseId: updated.id, submitterEmail: updated.respondentUpn, rowIndex });
      await addAuditEntry({
        formId: form.id,
        responseId: updated.id,
        byEmail: editorEmail,
        action: editorEmail === updated.respondentUpn ? "self-edit" : "admin-edit",
        changedFields,
        reason: params.reason,
      });
      return updated;
    } catch (err) {
      if (attempt === maxAttempts) {
        await markFailed(queueItemId, attempt, err instanceof Error ? err.message : String(err));
      } else {
        await sleep(500 * attempt);
      }
    }
  }

  return updated;
}

export async function getResponsesForForm(form: FormDefinition): Promise<ResponseRow[]> {
  return getResponseRows(form);
}
