import {
  appendResponseRow,
  getResponseByRowIndex,
  getResponseRows,
  updateResponseRow,
  type ResponseRow,
} from "./excel";
import { enqueueWrite, markDone, markFailed } from "./syncQueue";
import { getIndexBySubmitter, upsertIndex } from "./responseIndex";
import { addAuditEntry } from "./auditLog";
import {
  advanceRoutingState,
  getCurrentStep,
  getRoutingState,
  initRoutingState,
  resolveStepRecipients,
  saveRoutingState,
} from "./responseRouting";
import { sendApprovalRequest, sendRoutingOutcomeNotification } from "./routingMail";
import type { AnswerValue, AuditEntry, FormDefinition, FormResponse, ResponseRoutingState } from "../formsSchema/types";

function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/** Best-effort: notify whoever the current step's recipients resolve to.
 *  Never throws — a failed notification must not make the caller's
 *  submit/approve/reject action look like it failed (see routingMail.ts). */
async function notifyCurrentStep(form: FormDefinition, response: FormResponse): Promise<void> {
  const step = getCurrentStep(form, response.routing);
  if (!step) return;
  const recipients = resolveStepRecipients(step, response.answers);
  await Promise.all(
    recipients.map((email) =>
      sendApprovalRequest(email, form, response.id).catch((err) => {
        // eslint-disable-next-line no-console
        console.warn(`[routing] Could not email approval request to ${email}:`, err);
      })
    )
  );
}

function diffAnswers(
  before: Record<string, AnswerValue>,
  after: Record<string, AnswerValue>
): AuditEntry["changedFields"] {
  const fieldIds = new Set([...Object.keys(before), ...Object.keys(after)]);
  const changed: AuditEntry["changedFields"] = [];
  for (const fieldId of fieldIds) {
    const oldValue = before[fieldId] ?? null;
    const newValue = after[fieldId] ?? null;
    if (JSON.stringify(oldValue) !== JSON.stringify(newValue)) {
      changed.push({ fieldId, oldValue, newValue });
    }
  }
  return changed;
}

/**
 * Submits a fresh response: SyncQueue-first (durable regardless of what
 * happens next), then attempts the Excel append with a few retries. Even if
 * every Excel attempt fails, the response is NOT lost — it stays recorded in
 * SyncQueue as "failed" for the admin Sync Health page to recover, and the
 * caller still gets back a normal FormResponse rather than an error, matching
 * the plan's "tell the user submitted either way" durability model.
 */
export async function submitResponse(
  form: FormDefinition,
  answers: Record<string, AnswerValue>,
  respondentUpn: string,
  /** Pre-generated by the caller (FillRunner needs it up front for
   *  file-attachment upload paths) so it matches the id those files were
   *  actually uploaded under. Falls back to a fresh one if omitted. */
  responseId: string = crypto.randomUUID()
): Promise<FormResponse> {
  const now = new Date().toISOString();
  const response: FormResponse = {
    id: responseId,
    formId: form.id,
    formVersion: form.latestPublishedVersion ?? form.currentDraftVersion,
    respondentUpn,
    answers,
    status: "submitted",
    submittedAt: now,
    updatedAt: now,
    editHistory: [],
  };

  const queueItemId = await enqueueWrite({
    formId: form.id,
    responseId: response.id,
    submitterEmail: respondentUpn,
    operation: "insert",
    payload: response,
  });

  // Only the Excel write itself is retried here. appendResponseRow has no
  // idempotency check — it blindly appends a row every call — so once it
  // succeeds, nothing below may ever trigger another call to it. Previously
  // markDone/upsertIndex/addAuditEntry were inside this same retry unit:
  // if any of THEM threw (a throttled/network-blipped SharePoint List call,
  // unrelated to Excel), the catch retried the whole block, including the
  // already-succeeded appendResponseRow — silently appending a second row
  // for the same response while upsertIndex's own idempotency masked the
  // duplication from the index (it just repoints to the newer ghost row).
  const maxAttempts = 3;
  let rowIndex: number | null = null;
  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    try {
      rowIndex = await appendResponseRow(form, response);
      break;
    } catch (err) {
      // This was previously silent — a failure here only ever showed up as
      // a SyncQueue "failed" row on the admin Sync Health page, with no
      // console trace at all, making the underlying cause (e.g. a rejected
      // upload, a network/CORS error) invisible during live debugging.
      // eslint-disable-next-line no-console
      console.error("[submitResponse] appendResponseRow attempt failed", { attempt, maxAttempts, err });
      if (attempt === maxAttempts) {
        await markFailed(queueItemId, attempt, err instanceof Error ? err.message : String(err));
      } else {
        await sleep(500 * attempt);
      }
    }
  }

  if (rowIndex === null) {
    // Every attempt failed — already recorded as "failed" in SyncQueue above
    // for the admin Sync Health page to recover. Still return a normal
    // FormResponse, matching the "tell the user submitted either way"
    // durability model documented on this function.
    return response;
  }

  // The Excel write is done. Everything below is best-effort bookkeeping —
  // failures here must never loop back to appendResponseRow (see comment
  // above), so they're caught and logged, not retried as a unit.
  //
  // markDone runs LAST, deliberately: every recovery path (getUnresolved*,
  // the admin Sync Health page) filters on Status ne 'done', so if this ran
  // first and upsertIndex/addAuditEntry then failed, the item would be
  // permanently marked done with no way for anything to ever retry the
  // bookkeeping that didn't actually finish — losing the ResponseIndex
  // entry for good (next visit falls to "create" mode instead of "edit",
  // and a resubmission then duplicates the row, since appendResponseRow has
  // no idempotency check) or the audit trail entry, unrecoverably.
  try {
    await upsertIndex({ formId: form.id, responseId: response.id, submitterEmail: respondentUpn, rowIndex });
    await addAuditEntry({
      formId: form.id,
      responseId: response.id,
      byEmail: respondentUpn,
      action: "submit",
      changedFields: Object.entries(answers).map(([fieldId, newValue]) => ({ fieldId, oldValue: null, newValue })),
    });
    await markDone(queueItemId);
  } catch (err) {
    // eslint-disable-next-line no-console
    console.error("[submitResponse] post-write bookkeeping failed (response IS saved in Excel)", err);
  }

  // Routing kickoff is its own best-effort step — a response is fully
  // "submitted" whether or not its (optional) approval chain successfully
  // started.
  try {
    const routing = await initRoutingState(form, response.id);
    if (routing) {
      response.routing = routing;
      await addAuditEntry({
        formId: form.id,
        responseId: response.id,
        byEmail: respondentUpn,
        action: "route",
        changedFields: [],
      });
      await notifyCurrentStep(form, response);
    }
  } catch (err) {
    // eslint-disable-next-line no-console
    console.warn("[routing] Could not start approval routing for this response:", err);
  }

  return response;
}

/** The existing-response gate: does this email already have a response to
 *  this form? Email is the primary key, per the product's core requirement. */
export async function getMyResponse(
  form: FormDefinition,
  email: string
): Promise<{ response: FormResponse; rowIndex: number } | null> {
  const indexEntry = await getIndexBySubmitter(form.id, email);
  if (!indexEntry) return null;
  const response = await getResponseByRowIndex(form, indexEntry.fields.RowIndex);
  if (!response) return null;
  return { response, rowIndex: indexEntry.fields.RowIndex };
}

/**
 * Edits an existing response (self-edit or admin-edit — the caller decides
 * which based on the form's editPolicy and who's editing). Same SyncQueue-
 * first durability model as submitResponse, plus an audit trail entry
 * recording exactly what changed.
 */
export async function updateResponse(params: {
  form: FormDefinition;
  existing: FormResponse;
  rowIndexHint: number;
  answers: Record<string, AnswerValue>;
  editorEmail: string;
  reason?: string;
  /** Set by the approver-review flow (ApprovePage) — an approver editing
   *  fields is neither the original respondent nor a form admin, so the
   *  usual self-edit/admin-edit binary doesn't fit. Omit for the normal
   *  self-edit/admin-edit paths. */
  actionOverride?: "approver-edit";
}): Promise<FormResponse> {
  const { form, existing, answers, editorEmail } = params;
  const changedFields = diffAnswers(existing.answers, answers);

  const updated: FormResponse = {
    ...existing,
    answers,
    updatedAt: new Date().toISOString(),
  };

  const queueItemId = await enqueueWrite({
    formId: form.id,
    responseId: updated.id,
    submitterEmail: updated.respondentUpn,
    operation: "update",
    payload: updated,
  });

  // Same restructuring as submitResponse above, and for the same reason:
  // updateResponseRow overwrites by ResponseId rather than appending, so a
  // retry doesn't duplicate the row — but without this split, a
  // markDone/upsertIndex/addAuditEntry failure would retry the whole block
  // and call updateResponseRow again, double-incrementing EditCount and
  // overwriting LastEditedAt with the retry's timestamp for what the user
  // experiences as one single edit.
  const maxAttempts = 3;
  let rowIndex: number | null = null;
  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    try {
      rowIndex = await updateResponseRow(form, updated, params.rowIndexHint, editorEmail);
      break;
    } catch (err) {
      // eslint-disable-next-line no-console
      console.error("[updateResponse] updateResponseRow attempt failed", { attempt, maxAttempts, err });
      if (attempt === maxAttempts) {
        await markFailed(queueItemId, attempt, err instanceof Error ? err.message : String(err));
      } else {
        await sleep(500 * attempt);
      }
    }
  }

  if (rowIndex === null) return updated;

  // markDone last — see the matching comment in submitResponse above.
  try {
    await upsertIndex({ formId: form.id, responseId: updated.id, submitterEmail: updated.respondentUpn, rowIndex });
    await addAuditEntry({
      formId: form.id,
      responseId: updated.id,
      byEmail: editorEmail,
      action: params.actionOverride ?? (editorEmail === updated.respondentUpn ? "self-edit" : "admin-edit"),
      changedFields,
      reason: params.reason,
    });
    await markDone(queueItemId);
  } catch (err) {
    // eslint-disable-next-line no-console
    console.error("[updateResponse] post-write bookkeeping failed (edit IS saved in Excel)", err);
  }

  return updated;
}

export async function getResponsesForForm(form: FormDefinition): Promise<{ columns: string[]; rows: ResponseRow[] }> {
  return getResponseRows(form);
}

/**
 * Records an approver's decision (approve/reject) on a response — advances
 * or resolves the routing chain, logs it to the audit trail, and
 * best-effort notifies whoever needs to know next (the next step's
 * recipients, or the original respondent once the chain resolves). Field
 * edits an approver makes alongside their decision go through the normal
 * `updateResponse` path first (with `actionOverride: "approver-edit"`) —
 * this function only manages the routing state machine itself.
 */
export async function actOnRouting(params: {
  form: FormDefinition;
  response: FormResponse;
  actorEmail: string;
  action: "approved" | "rejected";
  reason?: string;
}): Promise<ResponseRoutingState> {
  const { form, response, actorEmail, action, reason } = params;
  const entry = await getRoutingState(form.id, response.id);
  if (!entry) throw new Error("This response has no approval routing in progress.");

  // ApprovePage's own recipient check is a UI-level gate only — this app has
  // no backend, so nothing stopped a signed-in org member from calling this
  // function directly (or writing to the ResponseRouting List item with
  // their own already-valid delegated token) to approve/reject someone
  // else's pending request, and even forge the actedBy value the history
  // would then display. Re-verify here, at the point the state-changing
  // write actually happens, so the UI check isn't the only thing standing
  // between "signed in" and "can decide any approval in the tenant."
  const currentStep = getCurrentStep(form, entry.state);
  const validRecipients = currentStep ? resolveStepRecipients(currentStep, response.answers) : [];
  if (!validRecipients.includes(actorEmail.trim().toLowerCase())) {
    throw new Error("You are not an authorized approver for this step.");
  }

  const nextState = advanceRoutingState(form, entry.state, actorEmail, action, reason);
  await saveRoutingState(entry.itemId, nextState);

  await addAuditEntry({
    formId: form.id,
    responseId: response.id,
    byEmail: actorEmail,
    action: action === "approved" ? "approve" : "reject",
    changedFields: [],
    reason,
  });

  const updatedResponse: FormResponse = { ...response, routing: nextState };
  if (nextState.status === "in-progress") {
    await notifyCurrentStep(form, updatedResponse);
  } else {
    await sendRoutingOutcomeNotification(response.respondentUpn, form, response.id, nextState.status, reason).catch((err) => {
      // eslint-disable-next-line no-console
      console.warn(`[routing] Could not email outcome to ${response.respondentUpn}:`, err);
    });
  }

  return nextState;
}
