import { useMemo, useState, type ReactNode } from "react";
import { RuntimeShell } from "./RuntimeShell";
import { FieldRenderer } from "./fields/FieldRenderer";
import { AutofillField } from "./fields/AutofillField";
import { ConnectorTableField } from "./fields/ConnectorTableField";
import { FileUploadField } from "./fields/FileUploadField";
import { GraphImage } from "../common/GraphImage";
import { getVisibleFields, resolveFirstSectionId, resolveNextSectionId, shuffleSectionOrder } from "../../formsSchema/branching";
import { validateFields, type FieldError } from "../../formsSchema/validation";
import { useAuth } from "../../auth/useAuth";
import type { AnswerValue, FormDefinition, FormField } from "../../formsSchema/types";

interface Props {
  form: FormDefinition;
  /** Stable id used for this response's file-attachment paths (and, once
   *  submitted, the response's own id) — generated by the caller so it's
   *  consistent from the first file upload through to the final submit. */
  responseId: string;
  initialAnswers?: Record<string, AnswerValue>;
  /** Omit (or pass []) for a fresh fill-out — FillRunner resolves the first
   *  visible section itself (respecting shuffleSections). Pass the actual
   *  path for resuming a draft/edit, so Back replays it exactly. */
  initialSectionIds?: string[];
  /** Shown as a banner above the form — e.g. "You already submitted this on
   *  <date>. Editing your response — changes are logged." for the edit-mode gate. */
  banner?: ReactNode;
  /** Edit policy's requireReasonForEdit — collects a short reason on the
   *  final step and passes it through to onSubmit. */
  requireReason?: boolean;
  /** "Save and finish later" — omitted entirely (no button shown) when not
   *  provided, e.g. in edit mode or builder Preview. */
  onSaveDraft?: (answers: Record<string, AnswerValue>, visitedSectionIds: string[]) => Promise<void>;
  /** Called after the last step validates successfully. Throw to surface an
   *  error inline instead of advancing (the runtime doesn't navigate away on
   *  its own — the caller decides what happens after a successful submit,
   *  which is what lets the builder's Preview mode reuse this unchanged). */
  onSubmit: (answers: Record<string, AnswerValue>, reason?: string) => Promise<void>;
}

/**
 * The shared page-by-page fill-out engine — used by the live `/f/:slug`
 * route (fresh submissions, edits, and resumed drafts) and the builder's
 * Preview mode, so preview and reality can't drift (per the plan's Builder
 * UX note).
 */
export function FillRunner({
  form,
  responseId,
  initialAnswers,
  initialSectionIds,
  banner,
  requireReason,
  onSaveDraft,
  onSubmit,
}: Props) {
  const { email } = useAuth();

  // Shuffle only affects the natural "next section in order" fallback —
  // branchRules/defaultNext (specific target ids) always take priority, so
  // this can't break configured branching. Computed once per mount.
  const effectiveSections = useMemo(
    () => (form.settings.shuffleSections ? shuffleSectionOrder(form.sections) : form.sections),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [form.id]
  );

  const [answers, setAnswers] = useState<Record<string, AnswerValue>>(initialAnswers ?? {});
  const [visitedSectionIds, setVisitedSectionIds] = useState<string[]>(() => {
    if (initialSectionIds && initialSectionIds.length > 0) return initialSectionIds;
    const first = resolveFirstSectionId(effectiveSections, initialAnswers ?? {});
    return first ? [first] : [];
  });
  const [errors, setErrors] = useState<FieldError[]>([]);
  const [reason, setReason] = useState("");
  const [reasonError, setReasonError] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);
  const [savingDraft, setSavingDraft] = useState(false);
  const [draftSaved, setDraftSaved] = useState(false);

  const currentSectionId = visitedSectionIds[visitedSectionIds.length - 1] ?? null;
  const currentSection = useMemo(
    () => effectiveSections.find((s) => s.id === currentSectionId) ?? null,
    [effectiveSections, currentSectionId]
  );
  const visibleFields = useMemo(
    () => (currentSection ? getVisibleFields(currentSection, answers) : []),
    [currentSection, answers]
  );

  if (!currentSection) {
    return (
      <RuntimeShell title={form.title} description={form.description} branding={form.branding}>
        <p>This form has no sections yet.</p>
      </RuntimeShell>
    );
  }

  function setAnswer(fieldId: string, value: AnswerValue) {
    setAnswers((prev) => ({ ...prev, [fieldId]: value }));
    setErrors((prev) => prev.filter((e) => e.fieldId !== fieldId));
    setDraftSaved(false);
  }

  function handleBack() {
    setVisitedSectionIds((prev) => prev.slice(0, -1));
    setErrors([]);
  }

  const isLastStep = resolveNextSectionId(currentSection.id, effectiveSections, answers) === null;

  async function handleSaveDraft() {
    if (!onSaveDraft) return;
    setSavingDraft(true);
    try {
      await onSaveDraft(answers, visitedSectionIds);
      setDraftSaved(true);
    } catch (err) {
      setSubmitError(err instanceof Error ? err.message : String(err));
    } finally {
      setSavingDraft(false);
    }
  }

  async function handleNext() {
    const fieldErrors = validateFields(visibleFields, answers);
    if (fieldErrors.length > 0) {
      setErrors(fieldErrors);
      return;
    }

    const nextId = resolveNextSectionId(currentSection!.id, effectiveSections, answers);
    if (nextId) {
      setVisitedSectionIds((prev) => [...prev, nextId]);
      return;
    }

    if (requireReason && reason.trim() === "") {
      setReasonError("Please give a short reason for this change.");
      return;
    }

    setSubmitting(true);
    setSubmitError(null);
    setReasonError(null);
    try {
      await onSubmit(answers, requireReason ? reason.trim() : undefined);
    } catch (err) {
      setSubmitError(err instanceof Error ? err.message : String(err));
    } finally {
      setSubmitting(false);
    }
  }

  const totalSections = Math.max(form.sections.length, 1);
  const progress = Math.min(1, visitedSectionIds.length / totalSections);

  return (
    <RuntimeShell title={form.title} description={form.description} branding={form.branding}>
      {banner && <div className="runtime__banner">{banner}</div>}

      {form.sections.length > 1 && form.settings.showProgressBar && (
        <div className="runtime__progress-track">
          <div className="runtime__progress-fill" style={{ width: `${progress * 100}%` }} />
        </div>
      )}

      {currentSection.imageUrl && (
        <GraphImage className="fill-runner__section-image" src={currentSection.imageUrl} alt="" />
      )}
      <h2 className="fill-runner__section-title">{currentSection.title}</h2>
      {currentSection.description && <p className="fill-runner__section-desc">{currentSection.description}</p>}

      {visibleFields.map((field) => renderField(field, answers, setAnswer, errors, email ?? "", form.id, responseId))}

      {isLastStep && requireReason && (
        <div className="fill-field">
          <label className="fill-field__label" htmlFor="edit-reason">
            Reason for this change<span className="fill-field__required-mark">*</span>
          </label>
          <input
            id="edit-reason"
            className="fill-field__input"
            type="text"
            value={reason}
            onChange={(e) => setReason(e.target.value)}
          />
          {reasonError && <div className="error-text">{reasonError}</div>}
        </div>
      )}

      {submitError && <p className="error-text">{submitError}</p>}

      <div className="fill-runner__nav">
        {visitedSectionIds.length > 1 ? (
          <button onClick={handleBack} disabled={submitting}>
            Back
          </button>
        ) : (
          <span />
        )}
        <span className="fill-runner__nav-spacer" />
        {onSaveDraft && (
          <button onClick={handleSaveDraft} disabled={savingDraft || submitting}>
            {savingDraft ? "Saving…" : draftSaved ? "Saved ✓" : "Save and finish later"}
          </button>
        )}
        <button className="btn-primary" onClick={handleNext} disabled={submitting}>
          {submitting ? "Submitting…" : isLastStep ? form.branding.submitButtonText || "Submit" : "Next"}
        </button>
      </div>
    </RuntimeShell>
  );
}

/** Dispatches each visible field to the renderer matching its fillMode/type. */
function renderField(
  field: FormField,
  answers: Record<string, AnswerValue>,
  setAnswer: (fieldId: string, value: AnswerValue) => void,
  errors: FieldError[],
  respondentEmail: string,
  formId: string,
  responseId: string
) {
  const error = errors.find((e) => e.fieldId === field.id)?.message;
  const onChange = (v: AnswerValue) => setAnswer(field.id, v);

  if (field.type === "repeatingTable") {
    return (
      <ConnectorTableField
        key={field.id}
        field={field}
        respondentEmail={respondentEmail}
        priorAnswers={answers}
        onChange={onChange}
        error={error}
      />
    );
  }

  // Checked BEFORE the fileUpload branch below: a fileUpload field can also
  // be configured with fillMode "graph-autofill"/"connector-autofill" (e.g.
  // auto-attach a reference document resolved by lookup key) — dispatching
  // on field.type first would silently ignore that config and always show
  // the plain manual uploader.
  if (field.fillMode !== "manual") {
    return (
      <AutofillField
        key={field.id}
        field={field}
        respondentEmail={respondentEmail}
        priorAnswers={answers}
        formId={formId}
        responseId={responseId}
        onChange={onChange}
        error={error}
      />
    );
  }

  if (field.type === "fileUpload") {
    return (
      <FileUploadField
        key={field.id}
        field={field}
        formId={formId}
        responseId={responseId}
        value={answers[field.id] ?? null}
        onChange={onChange}
        error={error}
      />
    );
  }

  return <FieldRenderer key={field.id} field={field} value={answers[field.id] ?? null} onChange={onChange} error={error} />;
}
